# Generated by Django 2.1.15 on 2020-03-20 05:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('domain', '0003_auto_20200320_0432'),
    ]

    operations = [
        migrations.CreateModel(
            name='VPS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pack', models.CharField(max_length=60, null=True)),
                ('vcpu', models.IntegerField(null=True)),
                ('ssd', models.IntegerField(null=True)),
                ('ram', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('price_1', models.IntegerField(null=True)),
                ('price_3', models.IntegerField(null=True)),
                ('price_6', models.IntegerField(null=True)),
                ('price_12', models.IntegerField(null=True)),
                ('price_1_usd', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('price_3_usd', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('price_6_usd', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('price_12_usd', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('link', models.CharField(max_length=100, null=True)),
                ('note', models.CharField(max_length=100, null=True)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='domain.Vendor')),
            ],
        ),
    ]
