# Generated by Django 2.1.15 on 2020-03-20 04:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('domain', '0003_auto_20200320_0432'),
    ]

    operations = [
        migrations.CreateModel(
            name='SSL',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ssl_type', models.CharField(choices=[('comodo', 'Comodo SSL'), ('geotrust', 'GeoTrust SSL'), ('symantec', 'Symantec SSL'), ('thawte', 'Thawte SSL'), ('globalsign', 'GlobalSign SSL')], default='comodo', max_length=10)),
                ('pack', models.CharField(max_length=60, null=True)),
                ('price', models.IntegerField()),
                ('validation_type', models.CharField(choices=[('DV', 'Domain Validation (DV)'), ('EV', 'Extended Validation (EV)'), ('OV', 'Organization Validation (OV)')], default='DV', max_length=30)),
                ('sans_support', models.CharField(max_length=60, null=True)),
                ('domain_secured', models.CharField(max_length=40, null=True)),
                ('warranty', models.CharField(max_length=15, null=True)),
                ('trust_level', models.CharField(choices=[('standard', 'Standard'), ('high', 'High'), ('highest', 'Highest'), ('unknown', 'Unknown')], default='standard', max_length=10)),
                ('validity_options', models.CharField(max_length=15, null=True)),
                ('support', models.BooleanField(default='True')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='domain.Vendor')),
            ],
        ),
    ]
